Updating descriptor and jenkinsfile

diff --git a/jenkins/anypoint-api-cataloging-example-cd.jenkinsfile b/jenkins/anypoint-api-cataloging-example-cd.jenkinsfile
--- a/jenkins/anypoint-api-cataloging-example-cd.jenkinsfile
+++ b/jenkins/anypoint-api-cataloging-example-cd.jenkinsfile
@@ -1,19 +1,20 @@
 #!groovy
 pipeline {
     agent any
+    tools {nodejs "NodeJs"}
     options {
         skipDefaultCheckout true
     }
     environment {
         BUILD_VERSION = "build.${currentBuild.number}"
-        CLIENT_ID = credentials('anypoint.platform.clientId')
-        CLIENT_SECRET = credentials('anypoint.platform.clientSecret')
+        CLIENT_ID = credentials('anypoint.platform.cataloging.clientId')
+        CLIENT_SECRET = credentials('anypoint.platform.cataloging.clientSecret')
         ANYPOINT_PLATFORM_ORG_ID = credentials('anypoint.platform.org.id')
     }
     parameters {
-        choice( name: 'BRANCH', choices: "master\ndevelop", description: 'Project branch' )
-        string( name: 'ANYPOINT_PLATFORM_URL', defaultValue: 'https://eu1.anypoint.mulesoft.com', description: 'URL for Anypoint Platform (Default: https://eu1.anypoint.mulesoft.com - Production Anypoint Platform)' )
-        choice( name: 'ENVIRONMENT', choices: "sandbox\nproduction", description: 'Environment where the API documentation will be deployed' )
+        string( name: 'BRANCH', defaultValue: "develop", description: 'Project branch' )
+        string( name: 'ANYPOINT_PLATFORM_URL', defaultValue: 'eu1.anypoint.mulesoft.com', description: 'URL for Anypoint Platform (Default: https://eu1.anypoint.mulesoft.com - Production Anypoint Platform)' )
+        string( name: 'ENVIRONMENT', defaultValue: "Sandbox", description: 'Environment where the API documentation will be deployed' )
     }
     stages{
         stage('Checkout Release') {
@@ -25,7 +26,7 @@ pipeline {
                     print "GitHub branch: " + branchName
                     echo "Checking out Release from GitHub..."
                     checkout([$class: 'GitSCM', 
-                            branches: [[name: "${params.BRANCH}"]], 
+                              branches: [[name: "${branchName}"]], 
                             doGenerateSubmoduleConfigurations: false, 
                             extensions: [], 
                             submoduleCfg: [], 
@@ -52,13 +53,24 @@ pipeline {
         stage('Cataloging API in Anypoint Platform') {
             steps {
                 script {
+                    def branchName = scm.branches[0].name
                     sh """cd api;
                         echo "Cataloging API in Anypoint Platform'";
-                        api-catalog publish-asset --descriptor-file=catalog.yaml \
+                        errorCode="Error";
+                        commandOutput=\$(api-catalog publish-asset --descriptor-file=catalog.yaml \
                         --host=${env.ANYPOINT_PLATFORM_URL} --organization=${env.ANYPOINT_PLATFORM_ORG_ID} \
                         --environment=${env.ENVIRONMENT} \
                         --client_id=${env.CLIENT_ID} --client_secret=${env.CLIENT_SECRET} \
-                        --trigger-criteria=branches:${branchName}"""   
+                        --trigger-criteria=branches:${branchName});
+                        if [[ \\"\$commandOutput\\" == *\\"\$errorCode\\"* ]]
+                            then
+                                echo "Error while Cataloging API - Please check the logs";
+                                exit 1;
+                            else
+                                echo "Success in Cataloging API";
+                                exit 0;
+                            fi
+                        """   
                 }
             }    
             post {
@@ -83,4 +95,4 @@ pipeline {
             echo "Pipeline currentResult: ${currentBuild.currentResult}"
         }
     }
-}  
+}
